name: Playwright Tests (junit)
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

    # Install your dependencies for your project & Testiny CLI:
    - name: Install dependencies
      run: |
        npm ci
        npm install --no-save @testiny/cli@latest
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run your automated tests & generate a report file
    - name: Run Playwright tests
      run: npx playwright test
      
    # Run CLI to upload results
    - name: Upload test results to Testiny
      if: ${{ !cancelled() }}
      env: 
        TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }}
      run: npx @testiny/cli automation --project 57 --source pw-tests --junit results/results.xml --custom-result-fields=type,some_link