name: Playwright Tests (reporter)
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm

      # Install your dependencies for your project & Testiny CLI:
    - name: Install dependencies
      run: |
        npm ci
        npm install --no-save @testiny/cli@latest
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Run your automated tests & directly upload results with Testiny reporter
    - name: Run Playwright tests
      env: 
        TESTINY_API_KEY: ${{ secrets.TESTINY_API_KEY }} # API key is used by Testiny reporter
      run: npx playwright test --config playwright-testiny-reporter.config.ts # reporter is configured in playwright config file and automatically reports to Testiny
